### PR TITLE
Use master branch for AppVeyor badge.

### PR DESCRIPTION
**Pull request by Roel**
Display the AppVeyor badge for the master branch, instead of the latest build.

### CODE REVIEW

**Comment by stijnvanhoey** [comment]
The appveyor error is due to the deprecation error on Python 2.7... Which raises the question: do we still want to maintain 2.7 up to January 1st, 2020?

**Comment by Roel** [comment]
Good question. The warning seems to be coming from pip 19.0: https://pip.pypa.io/en/stable/news/#id4

I'm unsure why it only fails in the 2.7 lxml build and not in the other 2.7 build however. And Travis doesn't seem to mind either..

I can take a look and experiment in the next few days.

**Comment by stijnvanhoey** [comment]
Nice, but it is not entirely clear to me what solved the issue of the 2.7 warning eventually?

**Comment by Roel** [comment]
I don't understand it completely either. This appears to be the magic combo that works (for now)..

**Pull request merged**
