### PR TITLE
Add ci file for github actions

### PR DESCRIPTION
**Pull request by stijnvanhoey**
* [ ] I have read and followed the guidelines in the `CONTRIBUTING` document
* [ ] I have checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change
* [ ] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.
* [ ] All new and existing tests passed.

Describe your fixes/additions/changes

### CODE REVIEW

**Comment by stijnvanhoey** [comment]
Current tryout of the Github actions tryout, but work in progress so do not yet merge. Some elements to consider:

- I tried with the existing `tox.ini` (no conda) for windows, but fails
- email-notification is not (yet) setup; e.g. https://github.com/marketplace/actions/send-email
- maybe we do not need to test the entire matrix of 4python x 3 os systems?

Note, I added a monthly cron-job (test jobs talking to pydov servers)

**Comment by stijnvanhoey** [comment]
@roel any idea on the failed test on windows 3.8?

```
FAILED tests/test_util_hooks.py::TestHookCount::test_wfs_and_xml_cache[plaintext_cache0]
```

**Comment by Roel** [comment]
Sometimes there are testfailures due to timeouts. I'm not sure why and haven't investigated this further yet. This is nothing new and happens in Appveyor and Travis too..

Regarding the PR: nice work! Some comments from my side:

- My initial plan to only replace our Windows (Appveyor) builds and keep Travis for the moment for the Linux builds (since this works mostly fine and has been set-up for the PyPi deployments etc.)

- Maybe we can drop a few Python versions, but if it's fast enough we might as well keep them?

- Travis runs a weekly cron, I think that might be more interesting than monthly. Weekly will likely leave time (enough) to fix things before they hit production.

- E-mail notifications would be handy, yes. I will look into this.

- Conda would be nice (I think that was the reason we setup a Windows job in the first place?)

**Comment by stijnvanhoey** [comment]
@Roel I added the conda checks for both windows and linux OS (so it captures both linux and conda users). It installs all the package dependencies with conda, the development dependencies with pip and runs the tests for Python 3.5, 3.7 and 3.8.

However, some remaining issues (apart from the connection time out one):
- pyproj errors on python 3.5 in in windows
- it seems that owslib is no longer supporting python 3.5, see [pypi](https://pypi.org/project/OWSLib/... whereas conda installs 0.19.2, it is not actually supported by pip, creating an error, hm... making it fail as well 

__Note__ I added also the pypi deplyment however not tested... to do for next release

**Comment by stijnvanhoey** [comment]
ok, the owslib in conda is solved...

remaining issue, beside the connection timeout is pyproj in python 3.5 on windows:

```
 Collecting pyproj
  Using cached pyproj-2.6.1.post1.tar.gz (545 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: 'D:\a\pydov\pydov\.tox\py35-lxml\Scripts\python.EXE' 'D:\a\pydov\pydov\.tox\py35-lxml\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\RUNNER~1\AppData\Local\Temp\tmpv5bhk9ja'
       cwd: C:\Users\RUNNER~1\AppData\Local\Temp\pip-install-nzjwcupf\pyproj
  Complete output (1 lines):
  proj executable not found. Please set the PROJ_DIR variable.For more information see: https://pyproj4.github.io/pyproj/stable/installation.html
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'D:\a\pydov\pydov\.tox\py35-lxml\Scripts\python.EXE' 'D:\a\pydov\pydov\.tox\py35-lxml\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\RUNNER~1\AppData\Local\Temp\tmpv5bhk9ja' Check the logs for full command output.
```

**Comment by Roel** [comment]
Looking good! As for the Python3.5 issue, I guess since OWSLib dropped support in their latest 0.19.2 bugfix (!) release, we have not much choice but to drop support in pydov too?

**Comment by stijnvanhoey** [comment]
> Looking good! As for the Python3.5 issue, I guess since OWSLib dropped support in their latest 0.19.2 bugfix (!) release, we have not much choice but to drop support in pydov too?

Indeed, I agree.

**Comment by Roel** [comment]
Ok, it should be safe to remove this from the CI pipeline then.

**Comment by Roel** [comment]
I created separate issues for the Python3.5 support (#280) and timeout issue (#279).

**Comment by Roel** [comment]
I think we can go ahead and merge this, the failures are timeouts and not related to the switch to GA. Timeout failures to be followed up in #279

**Pull request merged**
