### PR TITLE
Implement first draft for Boring

### PR DESCRIPTION
**Pull request by Roel**
* [x] I have read and followed the guidelines in the `CONTRIBUTING` document
* [x] I have checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change
* [x] I have updated the documentation accordingly.
* [x] I have added tests to cover my changes.
* [x] All new and existing tests passed.

As agreed in December, I started with a first implementation for boreholes only. With the version in this PR you should be able to query boreholes from the DOV webservices and get the result as a pandas DataFrame in the format that is described in the docs.

I added tests using local testdata and the PyTests monkeypatch functionality to overwrite calls to the remote webservices. Using local data we can be sure the tests run in all CI environments and be sure the data stays the same between runs. I added a script to replace the local data with a new download from the corresponding service, so we can update the testdata from time to time to check if everything still works.

I moved the original code out of the pydov package to prevent it from interfering with the test coverage statistics, but still keep it around for now. I also added an example folder with a few ways to use the BoringSearch class.

I think it might be good to give this first version a thorough review before going further with more datatypes (interpretations and groundwater types) or more features (caching XML responses f.ex.).

When merging I'd maybe suggest squashing, in order to get rid of all the detailed commits.

### CODE REVIEW

**Comment by pjhaest** [comment]
@Roel, I looked through the code and was really impressed by the extent of the methods you already provide. I can't wait to test and maybe add some additional options. But one question, I think we discussed this earlier: why not keep a seperate branch active until thoroughly tested/commented, instead of merging to the master already?

**Comment by Roel** [comment]
That slipped out of my mind. I created a separate branch and switched the base of this PR.

**Comment by pjhaest** [comment]
Ok, looking forward to the testing

**Comment by stijnvanhoey** [comment]
I did a quick first scan of the implementation. Nice work! I do like the setup with the query-based approach and +1 for the monkeypatch approach combined with an update from time to time. I'll do more in-depth testing at the beginning of february.

**Pull request merged**
