### PR TITLE
New tutorial

### PR DESCRIPTION
**Pull request by pjhaest**
* [x] I have read and followed the guidelines in the `CONTRIBUTING` document
* [x] I have checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change
* [x] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.
* [ ] All new and existing tests passed.

Describe your fixes/additions/changes
A new tutorial was added to the notebooks. I tried to include most of the interesting pydov features and necessary workflows so far. No graphics since not part of pydov. Looking forward to suggestions/comments.

### CODE REVIEW

**Comment by stijnvanhoey** [comment]
Nice work @pjhaest. 

I maybe would not include the 'changes'  in the other notebooks, e.g. `search_boringen.ipynb ` as these are only differences because of the different runitme/conda env settings. Maybe also keep it lowercase in the name > introduct... instead of Introd.... to be more consistent with other notebooks.

**Comment by pjhaest** [comment]
@stijnvanhoey ok, thx. About the runtime settings of the other Notebooks, I just delete the files form this PR?  
Checks for some distributions were not successfull for tox targets. Not my cup of tea. Should this be resolved or not?

**Comment by stijnvanhoey** [comment]
> Checks for some distributions were not successfull for tox targets. Not my cup of tea. Should this be resolved or not?

The failures are due to network issues, as reported in https://github.com/DOV-Vlaanderen/pydov/issues/279 and not related to this PR so not blocking to merge. 

Maybe good to have @Roel have an additional check on the tutorial?

**Comment by Roel** [comment]
Sorry for the late response, I was on holiday for most of the last three weeks :)
I have some time to review this weekend!

**Comment by Roel** [comment]
I made some minor changes, nothing groundbreaking.

However I'm not sure if this tutorial is different (enough) from the ones we already have? Maybe we need some more background information about the datasets themselves and why one should query one or another? Ideally we'd have a detailed real-world example analysis from one of our users where they explain how they went about gathering the data they needed.

Maybe this is a good time to take another look at the work [Sarah did last year](https://github.com/DOV-Vlaanderen/pydov/commit/0ccb28ac2b2aea1211dc729860f760768af8c709)?

**Comment by pjhaest** [comment]
Thx for the reviews.  
In this 'introductory tutorial' I tried to touch as much aspects of pydov as possible while keeping it readable. Indeed, it is not that different from the other notebooks, just putting the most important aspects together (reference to defined objects, searches for attributes and location, caching and Timestamp).   
This notebook was setup with the aim of showing the different search options for a real-world example in hydrogeology. While the notebooks of Sarah illustrate the results of a specific search with more visualization in a different environment. I can add more visualizations to the notebook, requiring  folium or geopandas/contextily. But especially the latter is not that easy to get going I noticed.  
I believe the notebooks of Sarah show a nice application of pydov, but are less suited as a general introductory tutorial? As you may remember, I would still like to write this out with more examples. Work in progress.

**Comment by Roel** [comment]
I think you're right, we shouldn't make the introductory tutorial too complex either. I'm good merging this, so we can proceed with the pyOpenSci review process. If we get more ideas or comments there we can always include them in a next PR.

Thanks!

**Pull request merged**
