### PR TITLE
Hex logo

### PR DESCRIPTION
**Pull request by peterdesmet**
* [x] I have read and followed the guidelines in the `CONTRIBUTING` document
* [x] I have checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change: **would replace #117**
* [x] I have updated the documentation accordingly: **logo included in README following layout used for R packages: 266a05d0eac7ecdb9240b0c59d0a9ee34e63b88a. Unfortunately a bit more cumbersome than in markdown.**
* [x] I have added tests to cover my changes: **n/a**
* [x] All new and existing tests passed: **not tested**

Added a hex logo, see #116.

- Location of file: I don't think there is a convention, but it seemed to make sense in the root or in `docs/_static/img`. I chose the latter.
- Logo added to `conf.py` as per [conf.py instructions](https://www.sphinx-doc.org/en/stable/usage/configuration.html#confval-html_logo ), but couldn't test docs build: got stuck with `Running setup.py bdist_wheel for pyproj` trying to `pip install -r requirements_doc.txt`.

### CODE REVIEW

**Comment by stijnvanhoey** [comment]
When checking the built version, https://pydov.readthedocs.io/en/hex_logo/, the image is not rendered well on the right hand side. Considering issue #97 as well, I propose to split the github-repo README.md and the sphinx readme.rst, although this is against the DRY idea, as it:
- overcomes the internal links issue of #97 
- enables easy incorporation of the image into the readme.md file (not with `raw_html` block) and keeping sphinx setup as normal
@Roel and @pjhaest  ok? I'll provide an updat on this PR with a split of the readme-files if ok.

Furthermore, should we change de default readthedocs blue to better match the yellow of the logo?

**Comment by Roel** [comment]
I think splitting up the two makes sense. This would also allow f.ex. to keep the badges only in the (Github) README.md and keeping this really minimal, linking to the docs for further information.

Personally I don't mind the blue in RTD.

**Comment by peterdesmet** [comment]
:+1: for splitting.

My suggestion for a README:

> # title + logo
> badges
> 
> pydov is a Python package to query and download data from [Databank Ondergrond Vlaanderen (DOV)](https://dov.vlaanderen.be/dovweb/html/index.html). It is hosted on [GitHub](https://github.com/DOV-Vlaanderen/pydov) and development is coordinated by Databank Ondergrond Vlaanderen (DOV). DOV aggregates data about soil, subsoil and groundwater of Flanders and makes them publicly available. Interactive and human-readable extraction and querying of the data is provided by a [web application](https://www.dov.vlaanderen.be/portaal/?module=verkenner#ModulePage), whereas the focus of this package is to **support machine-based extraction and conversion of the data**.
> 
> To get started, see the documentation at https://pydov.readthedocs.io.
> 
> ## Meta
> 
> * We welcome [contributions](https://github.com/DOV-Vlaanderen/pydov/blob/hex_logo/CONTRIBUTING.rst) including bug reports.
> * License: MIT
> * Please note that this project is released with a [Contributor Code of Conduct](https://github.com/DOV-Vlaanderen/pydov/blob/hex_logo/CONDUCT.rst). By participating in this project you agree to abide by its terms.


Would keep with default blue, as that is closely similar to blue used in Flemish Government websites + links.

@stijnvanhoey: any technical reason why CONTRIBUTING.rst and CONDUCT.rst (incorrect name for GitHub to recognize) are not part of the `.github` directory?

**Comment by pjhaest** [comment]
Ok with splitting. Would be nice to see #97 solved :+1:

**Comment by stijnvanhoey** [comment]
@Roel and @pjhaest can you have a look at:
- https://pydov.readthedocs.io/en/hex_logo/ - the frontpage of the documentation
- https://github.com/dov-vlaanderen/pydov/tree/hex_logo - the readme of the package on Github
(I kept badges on both)

**Comment by pjhaest** [comment]
looking good, adjusted some minor spellings :+1:

**Comment by stijnvanhoey** [comment]
Thanks, indeed good to use lowercase pydov consistently.

**Pull request merged**
