### PR TITLE
Grondmonster

### PR DESCRIPTION
**Pull request by pjhaest**
* [x] I have read and followed the guidelines in the `CONTRIBUTING` document
* [x] I have checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change
* [x] I have updated the documentation accordingly.
* [x] I have added tests to cover my changes.
* [x] All new and existing tests passed.

The datatype Grondmonster is available with the subtypes for which information is now mostly available. The subtypes 'mechanisch', 'chemisch' and 'steenkoolanalyse' are not yet included

### CODE REVIEW

**Comment by pjhaest** [comment]
@Roel : thanks for the final cleanup. Ok to merge?

**Comment by Roel** [comment]
I was going to update the test data once more, and then I think we're ready for merge :)

**Comment by pjhaest** [comment]
please feel free to merge when you're ready :+1:

**Comment by Roel** [comment]
Merged, thanks again!

**Pull request merged**
