### PR TITLE
proposal for PyDOV logo

### PR DESCRIPTION
**Pull request by pjhaest**
* [x] I have read and followed the guidelines in the `CONTRIBUTING` document
* [x] I have checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change
* [ ] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.
* [ ] All new and existing tests passed.

proposal for a PyDOV logo, all comments, changes, new proposals are welcome
@peterdesmet: Stijn mentioned your designer qualities, looking forward to improvements

### CODE REVIEW

**Comment by pjhaest** [comment]
Forgot to add that I don't have access to the Flanders Art Serif. Someone with access will need to change the chosen font.
This PR is discussed in issue #116

**Comment by stijnvanhoey** [comment]
I'm bringing in @peterdesmet to the discussion, as he is more experienced in the design of proper logo's. One option would be to go for the hexagon style as is regularly used elsewhere, see http://hexb.in/

**Comment by peterdesmet** [comment]
Sorry, my mistake: didn’t see #116

**Comment by pjhaest** [comment]
closing, see #119 for follow-up

**Pull request closed without merging**
