### PR TITLE
Bodemdata code

### PR DESCRIPTION
**Pull request by jorissynaeve**
* [x] I have read and followed the guidelines in the `CONTRIBUTING` document
* [x] I have checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change
* [x] I have updated the documentation accordingly.
* [x] I have added tests to cover my changes.
* [ ] All new and existing tests passed.

Implementation of bodem-objects.

! 1 of the tests is failing because timeout.

Please get your opinion of the bodem-objects.

### CODE REVIEW

**Comment by Roel** [comment]
The remaining test failure is because some things are only changed in production and not in oefen, so once oefen is fixed the tests should pass.

Once you think this is ready(ish), don't hesitate to remove the 'draft' status of this PR.

**Comment by jorissynaeve** [comment]
I found the problem in the tests and running the tests again.

The tests thinks the data in oefen should be the same as in production, so an observation with a permkey A in oefen is the same as the observation with permkey A in production. But that's not true (and it should not in my opinion).

**Comment by jorissynaeve** [comment]
I think i misunderstand the test-error
`for field in list(df):
  >           mandatory = fields[field]['notnull']
  E           KeyError: 'pkey_bodemsite'`

While pkey_bodemsite is available in oefen and production for bodemlocatie 2011-000002
`<bodem:Bodemsitefiche>
https://www.dov.vlaanderen.be/data/bodemsite/2011-000245
</bodem:Bodemsitefiche>`
`<bodem:Bodemsitefiche>
https://oefen.dov.vlaanderen.be/data/bodemsite/2011-000245
</bodem:Bodemsitefiche>`

**Comment by Roel** [comment]
> I think i misunderstand the test-error
> `for field in list(df):
> 
> > ```
> >       mandatory = fields[field]['notnull']
> > ```
> 
> E KeyError: 'pkey_bodemsite'`
> 
> While pkey_bodemsite is available in oefen and production for bodemlocatie 2011-000002
> `<bodem:Bodemsitefiche> https://www.dov.vlaanderen.be/data/bodemsite/2011-000245 </bodem:Bodemsitefiche>`
> `<bodem:Bodemsitefiche> https://oefen.dov.vlaanderen.be/data/bodemsite/2011-000245 </bodem:Bodemsitefiche>`

I think the problem is that it is missing in the feature catalogue in oefen: https://oefen.dov.vlaanderen.be/geonetwork/srv/dut/catalog.search#/metadata/3f507fd9-24c0-40ab-9328-29f0dff571fe

**Comment by debaetpa** [comment]
The field 'Bodemsitefiche' was added to the oefen feature catalogue.

**Review by Roel — APPROVED** [review]
I think this is ready for merging now.

@jorissynaeve can you do a final check?

**Comment by jorissynaeve** [comment]
Thanks @Roel for verify this branch.
I did a final check and for me it's ok to merging.

**Pull request merged**
