### PR TITLE
Update docs minor

### PR DESCRIPTION
**Pull request by pjhaest**
* [x] I have read and followed the guidelines in the `CONTRIBUTING` document
* [x] I have checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change
* [x] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.
* [ ] All new and existing tests passed.

Describe your fixes/additions/changes
baby update to the docs with PyDOV --> pyDOV and added email

### CODE REVIEW

**Comment by Roel** [comment]
Is there a specific reason to change "PyDOV" to "pyDOV"? I ask because it is listed in more places in the documentation than the README, so we should change it everywhere in that case.

**Comment by pjhaest** [comment]
Ok, I just noticed while scrolling through and changed this because it was discussed in the juni code sprint. I will change other occurrences as well (only a bit confusing with capitals at the start of a sentence ;-) )

**Comment by Roel** [comment]
I don't remember discussing this, and I personally find the version with uppercase a little clearer. But if we agreed to this change, please go ahead :)

**Comment by Roel** [comment]
I agree that the name of the package itself should be all lowercase as described in PEP8.

However I think the discussion here is whether we distinguish between the name of the "project" and the name of the "package"?

**Comment by Roel** [comment]
I think more projects do it this way. I'm personally more in favor of "PyDOV", which has the added benefit that this is how it's currrently written everywhere in the docs :)

**Comment by pjhaest** [comment]
Ok, it's pyDOV in the proceedings of Geologica Belgica (that's why I got mixed up). But we'll create an additional reference then, more focussed on the code itself.

**Pull request merged**
